# This is a Jupyter Notbook. 
You can run python code blocks/cells by 
- clicking the **triangular "Run"** button at the top right of a cell 
- or by pressing **Shift + Enter** when a cell is selected.

# Task 0: Python Basics

In this task, you will learn the fundamental building blocks of Python programming. For every concept needed in the upcoming tasks, there is an example code cell below. Please experiment by changing values, variable names, and operators. If Python encounters something it cannot process, it will display an error message — use this information to troubleshoot! You can always ask the tutors for help, but also try to use Google and the Python documentation. Searching for errors and solutions online is a big part of coding!

Let's start simple: you can run code in a cell by pressing **Shift + Enter**. Try it out with the cell below!

In [5]:
print("Im a hacker now!")

Im a hacker now!


## 1. Creating Variables
The basics of all programming is the creation of variables. Variables are stored in memory until the Jupyter Notebook kernel is restarted or the variable is deleted. The Jupyter kernel runs Python in the background and executes the code you write in the cells.

In Python, we can define variable types (integers, floats, strings, lists), but often Python figures out the type automatically.
We use the `=` sign to assign values.

In [ ]:
# Create variables a and b
a = 5
b = 10

# TODO: Calculate the sum of a and b and store it in a variable called 'result'
result = ...
print(f"a = {a}, b = {b}, result = {result}")

a = 5, b = 10, result = 15


## 2. Lists and Arrays
Variables can hold more than single numbers. 
In Python, the standard container is a **list**. A list can contain numbers, strings (text), or even other lists!

Using lists or arrays allows us to store multiple values and perform operations on them at once, e.g., addition, multiplication, etc. This is especially useful when dealing with large datasets or performing mathematical computations.

In [ ]:
# A standard python list. 
mylist = [1, 4, 6, 2, 3, 8, 9]
print("List:", mylist)

# The position of the value determines its place in the list.
print("First element of the list:", mylist[0])

List: [1, 4, 6, 2, 3, 8, 9]
First element of the list: 1


### Using NumPy Arrays
For scientific computing, we almost always use **NumPy arrays** (vectors/matrices), which are more efficient for numerical operations. **NumPy** is a powerful library for numerical computing in Python.

To use a function from NumPy, we first need to import the library. Afterwards we use a function by writing `np.function_name()`. Inside the parentheses we provide the necessary input arguments for the function. In this case we only provide one argument, but if multiple arguments are needed, we separate them by commas `,`.

In [ ]:
# Importing NumPy package
# imported package renamed to np
import numpy as np

# TODO: Convert the list 'mylist' to a NumPy array using np.array()
myvec = ...
print("Numpy Array:", myvec)

Numpy Array: [1 4 6 2 3 8 9]


### Creating Ranges
To create a sequence of numbers automatically, we can use range functions.

In Python (NumPy): `np.arange(start, stop, step)`.

**Important**: The `stop` value is **excluded** in Python!

In [ ]:
# Create a vector from 0 to 9 (10 elements)
# Note: Python starts counting at 0 by default
vec_range = np.arange(0, 10)
print("Range 0-10 (exclusive):", vec_range)

# TODO: Create a range of even numbers from 2 to 20 (inclusive) using np.arange()
# Hint: np.arange(start, stop, step) — remember stop is excluded!
myreg = ...
print("Stepped range:", myreg)

Range 0-10 (exclusive): [0 1 2 3 4 5 6 7 8 9]
Stepped range: [ 2  4  6  8 10 12 14 16 18 20]


## 3. Matrices
A matrix is just a 2D array that can be created concatenating multiple lists/arrays.

In [10]:
# Creating a matrix manually
mymat = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("Matrix:\n", mymat)

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 4. Loading Data
We can load data saved in `.csv` files using `pandas`.
 
- **Pandas** provides data structures and functions for working with structured data, such as tables. It is commonly used for data manipulation and analysis.


In [11]:
# example dictionary
example_dict = {
    'key1': 'value1',
    'randomkey': [1, 2, 3],
    42: 'answer'
}

In [12]:
import pandas as pd

# Load the CSV file (new data source since .mat was deleted)
mymagic = pd.read_csv('magic.csv').to_numpy() # Convert to numpy array for consistency with previous data structures
print("Loaded data from CSV")

# If you have the extension "Data Wrangler" installed,
# you can look at the data by clicking on "Open 'mymagic' in Data Wrangler"
mymagic

Loaded data from CSV


array([[17, 24,  1,  8, 15],
       [23,  5,  7, 14, 16],
       [ 4,  6, 12, 20, 22],
       [10, 12, 19, 21,  3],
       [11, 18, 25,  2,  9]])

In [13]:
# As you can see, the matrix has 5 rows and 5 columns. 
# Instead of counting you can also check the shape of the matrix:
print("Shape of mymagic:", mymagic.shape)

Shape of mymagic: (5, 5)


## 5. Indexing and Slicing
Now let's try indexing and slicing on the loaded data.

- **Indexing**: Accessing a single element from a list, array, or matrix using its position.
- **Slicing**: Accessing a subset of elements using a range of positions.

**Important Rules**: 
1. Python indices start at **0** (the first element has index 0).
2. Slicing `start:end` **excludes** the `end` value.
3. Use square brackets `[]`, not parentheses `()`.
4. Step size can be specified with `start:end:step`.
5. Negative indices count from the end: `-1` is the last element, `-2` is the second-to-last, etc.
6. A colon `:` by itself selects the full range for that dimension.

In [ ]:
# TODO: Access row 5, column 4 of mymagic (remember: Python indices start at 0!)
val = ...
print("Value at row 5, col 4:", val)

# TODO: Change this value to 999
mymagic[..., ...] = 999
print("Updated value:", mymagic[4, 3])

Value at (4,3): 2
Updated value at (4,3): 999


In [15]:
# Access first row (index 0)
row1 = mymagic[0, :]
print("First row:", row1)

First row: [17 24  1  8 15]


In [16]:
# Access a block (Rows 0-3, Columns 0-2)
block = mymagic[0:4, 0:3]
print("Top left block:\n", block)

Top left block:
 [[17 24  1]
 [23  5  7]
 [ 4  6 12]
 [10 12 19]]


In [17]:
# Show every 2nd row and every 3rd column
subsampled = mymagic[::2, ::3]
print("Subsampled matrix:\n", subsampled)

Subsampled matrix:
 [[ 17   8]
 [  4  20]
 [ 11 999]]


## 6. Pandas

**Pandas** provides DataFrames, which are like tables with labeled rows and columns. Unlike NumPy arrays, DataFrames can have column names and handle mixed data types easily. We already used pandas to load the CSV file earlier with `pd.read_csv()`. Let's see how to work with the magic data as a DataFrame.

In [19]:
# Load the magic data as a pandas DataFrame instead of converting to NumPy
magic_df = pd.read_csv('magic.csv')
print("Magic square as DataFrame:")
print(magic_df)
print("\nAccess column by name:")
# set column names for easier access
magic_df.columns = ['Col1', 'Col2', 'Col3', 'Col4', 'Col5']
print(magic_df['Col1'])  # Access first column
print("\nDataFrame shape:", magic_df.shape)

Magic square as DataFrame:
   column1  column2  column3  column4  column5
0       17       24        1        8       15
1       23        5        7       14       16
2        4        6       12       20       22
3       10       12       19       21        3
4       11       18       25        2        9

Access column by name:
0    17
1    23
2     4
3    10
4    11
Name: Col1, dtype: int64

DataFrame shape: (5, 5)


### Slicing DataFrames
- You can slice DataFrames using the `.loc[]` and `.iloc[]` methods.
- `.loc[]` is label-based, meaning you can slice using row and column labels.
- `.iloc[]` is integer-based, meaning you can slice using row and column indices.

In [22]:
# Example of slicing a DataFrame using .loc
print("Slicing with loc:")
print(magic_df.loc[0:5, 'Col1':'Col2'])  # First 3 rows and columns 'Col1' to 'Col2'
print("\n")

# Example of slicing a DataFrame using .iloc 
print("Slicing with iloc:")
print(magic_df.iloc[0:3, 0:2])  # First 3 rows and first 2 columns

Slicing with loc:
   Col1  Col2
0    17    24
1    23     5
2     4     6
3    10    12
4    11    18


Slicing with iloc:
   Col1  Col2
0    17    24
1    23     5
2     4     6


## 7. Logic
Logical operators return booleans.

In [ ]:
print("1 == 2:", 1 == 2)
print("1 > 0:", 1 > 0)

# Logical indexing on arrays
myvec = np.arange(1, 11)

1 == 2: False
1 > 0: True


We can use logical operators to create boolean arrays that can be used to index other arrays. This is called **boolean indexing** and is a powerful way to filter data based on conditions.

In [ ]:
# TODO: Create a boolean vector that is True where myvec >= 5
logvec = ...
print("Original:", myvec)
print("Where >= 5:", logvec)
print("Values >= 5:", myvec[logvec])

Original: [ 1  2  3  4  5  6  7  8  9 10]
Where >= 5: [False False False False  True  True  True  True  True  True]
Values >= 5: [ 5  6  7  8  9 10]


## 8. Get Help
If you want to learn more about a function you can use the `help()` function or append `?` to the function name. This will give you information about the function, its parameters, and usage.

In [ ]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method

## 9. Test your skills

1. Find a function to sum all values in a matrix from the numpy library and get help on how to use it.
2. Use this function to calculate the sum of the center 3x3 block of the magic square matrix loaded before.
3. Use the same function to calculate the sum of all rows.

### Get Help

In [ ]:
help(np.sum)

Help on _ArrayFunctionDispatcher in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis. If
        axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In that case, if `a` is signed th

### Calculate center 3x3 block sum

In [ ]:
mymagic

array([[ 17,  24,   1,   8,  15],
       [ 23,   5,   7,  14,  16],
       [  4,   6,  12,  20,  22],
       [ 10,  12,  19,  21,   3],
       [ 11,  18,  25, 999,   9]])

In [ ]:
# TODO: Calculate the sum of the center 3x3 block of mymagic
# Hint: The center 3x3 block uses rows 1 to 3 and columns 1 to 3
blocksum = ...
print("Sum of center 3x3 block:", blocksum)

Sum of center 3x3 block: 116


### Calculate sum of all rows

In [ ]:
# TODO: Calculate the sum of each row of mymagic
# Hint: Use np.sum() with the axis parameter. axis=1 means "sum along columns for each row"
row_sums = ...
print("Sum of each row:", row_sums)

Sum of each row: [  65   65   64   65 1062]


---

## Congratulations! 🎉

You have successfully completed **Task 0: Python Basics**!

You've learned the fundamental skills needed for the upcoming exercises:
1. ✅ Creating and working with variables
2. ✅ Using lists, arrays, and matrices (NumPy)
3. ✅ Loading data from CSV files (Pandas)
4. ✅ Indexing and slicing data structures
5. ✅ Working with DataFrames
6. ✅ Using logical operators and boolean indexing
7. ✅ Finding help and documentation

These are essential programming skills that you'll use throughout the remaining tasks. You're now ready to tackle real neuroscience data analysis!

**Ready for Task 1!** 🚀